package com.jeffbruma.stemutility.numbersystem

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class SedenionTest {
    private val e = listOf(
        Sedenion(s0 = 1),
        Sedenion(s1 = 1),
        Sedenion(s2 = 1),
        Sedenion(s3 = 1),
        Sedenion(s4 = 1),
        Sedenion(s5 = 1),
        Sedenion(s6 = 1),
        Sedenion(s7 = 1),
        Sedenion(s8 = 1),
        Sedenion(s9 = 1),
        Sedenion(sA = 1),
        Sedenion(sB = 1),
        Sedenion(sC = 1),
        Sedenion(sD = 1),
        Sedenion(sE = 1),
        Sedenion(sF = 1),
    )

    @Test
    fun `multiplication table for sedenions`() {
        assertTrue(e[0] * e[0] == e[0])
        assertTrue(e[0] * e[1] == e[1])
        assertTrue(e[0] * e[2] == e[2])
        assertTrue(e[0] * e[3] == e[3])
        assertTrue(e[0] * e[4] == e[4])
        assertTrue(e[0] * e[5] == e[5])
        assertTrue(e[0] * e[6] == e[6])
        assertTrue(e[0] * e[7] == e[7])
        assertTrue(e[0] * e[8] == e[8])
        assertTrue(e[0] * e[9] == e[9])
        assertTrue(e[0] * e[10] == e[10])
        assertTrue(e[0] * e[11] == e[11])
        assertTrue(e[0] * e[12] == e[12])
        assertTrue(e[0] * e[13] == e[13])
        assertTrue(e[0] * e[14] == e[14])
        assertTrue(e[0] * e[15] == e[15])
        assertTrue(e[1] * e[0] == e[1])
        assertTrue(e[1] * e[1] == -e[0])
        assertTrue(e[1] * e[2] == e[3])
        assertTrue(e[1] * e[3] == -e[2])
        assertTrue(e[1] * e[4] == e[5])
        assertTrue(e[1] * e[5] == -e[4])
        assertTrue(e[1] * e[6] == -e[7])
        assertTrue(e[1] * e[7] == e[6])
        assertTrue(e[1] * e[8] == e[9])
        assertTrue(e[1] * e[9] == -e[8])
        assertTrue(e[1] * e[10] == -e[11])
        assertTrue(e[1] * e[11] == e[10])
        assertTrue(e[1] * e[12] == -e[13])
        assertTrue(e[1] * e[13] == e[12])
        assertTrue(e[1] * e[14] == e[15])
        assertTrue(e[1] * e[15] == -e[14])
        assertTrue(e[2] * e[0] == e[2])
        assertTrue(e[2] * e[1] == -e[3])
        assertTrue(e[2] * e[2] == -e[0])
        assertTrue(e[2] * e[3] == e[1])
        assertTrue(e[2] * e[4] == e[6])
        assertTrue(e[2] * e[5] == e[7])
        assertTrue(e[2] * e[6] == -e[4])
        assertTrue(e[2] * e[7] == -e[5])
        assertTrue(e[2] * e[8] == e[10])
        assertTrue(e[2] * e[9] == e[11])
        assertTrue(e[2] * e[10] == -e[8])
        assertTrue(e[2] * e[11] == -e[9])
        assertTrue(e[2] * e[12] == -e[14])
        assertTrue(e[2] * e[13] == -e[15])
        assertTrue(e[2] * e[14] == e[12])
        assertTrue(e[2] * e[15] == e[13])
        assertTrue(e[3] * e[0] == e[3])
        assertTrue(e[3] * e[1] == e[2])
        assertTrue(e[3] * e[2] == -e[1])
        assertTrue(e[3] * e[3] == -e[0])
        assertTrue(e[3] * e[4] == e[7])
        assertTrue(e[3] * e[5] == -e[6])
        assertTrue(e[3] * e[6] == e[5])
        assertTrue(e[3] * e[7] == -e[4])
        assertTrue(e[3] * e[8] == e[11])
        assertTrue(e[3] * e[9] == -e[10])
        assertTrue(e[3] * e[10] == e[9])
        assertTrue(e[3] * e[11] == -e[8])
        assertTrue(e[3] * e[12] == -e[15])
        assertTrue(e[3] * e[13] == e[14])
        assertTrue(e[3] * e[14] == -e[13])
        assertTrue(e[3] * e[15] == e[12])
        assertTrue(e[4] * e[0] == e[4])
        assertTrue(e[4] * e[1] == -e[5])
        assertTrue(e[4] * e[2] == -e[6])
        assertTrue(e[4] * e[3] == -e[7])
        assertTrue(e[4] * e[4] == -e[0])
        assertTrue(e[4] * e[5] == e[1])
        assertTrue(e[4] * e[6] == e[2])
        assertTrue(e[4] * e[7] == e[3])
        assertTrue(e[4] * e[8] == e[12])
        assertTrue(e[4] * e[9] == e[13])
        assertTrue(e[4] * e[10] == e[14])
        assertTrue(e[4] * e[11] == e[15])
        assertTrue(e[4] * e[12] == -e[8])
        assertTrue(e[4] * e[13] == -e[9])
        assertTrue(e[4] * e[14] == -e[10])
        assertTrue(e[4] * e[15] == -e[11])
        assertTrue(e[5] * e[0] == e[5])
        assertTrue(e[5] * e[1] == e[4])
        assertTrue(e[5] * e[2] == -e[7])
        assertTrue(e[5] * e[3] == e[6])
        assertTrue(e[5] * e[4] == -e[1])
        assertTrue(e[5] * e[5] == -e[0])
        assertTrue(e[5] * e[6] == -e[3])
        assertTrue(e[5] * e[7] == e[2])
        assertTrue(e[5] * e[8] == e[13])
        assertTrue(e[5] * e[9] == -e[12])
        assertTrue(e[5] * e[10] == e[15])
        assertTrue(e[5] * e[11] == -e[14])
        assertTrue(e[5] * e[12] == e[9])
        assertTrue(e[5] * e[13] == -e[8])
        assertTrue(e[5] * e[14] == e[11])
        assertTrue(e[5] * e[15] == -e[10])
        assertTrue(e[6] * e[0] == e[6])
        assertTrue(e[6] * e[1] == e[7])
        assertTrue(e[6] * e[2] == e[4])
        assertTrue(e[6] * e[3] == -e[5])
        assertTrue(e[6] * e[4] == -e[2])
        assertTrue(e[6] * e[5] == e[3])
        assertTrue(e[6] * e[6] == -e[0])
        assertTrue(e[6] * e[7] == -e[1])
        assertTrue(e[6] * e[8] == e[14])
        assertTrue(e[6] * e[9] == -e[15])
        assertTrue(e[6] * e[10] == -e[12])
        assertTrue(e[6] * e[11] == e[13])
        assertTrue(e[6] * e[12] == e[10])
        assertTrue(e[6] * e[13] == -e[11])
        assertTrue(e[6] * e[14] == -e[8])
        assertTrue(e[6] * e[15] == e[9])
        assertTrue(e[7] * e[0] == e[7])
        assertTrue(e[7] * e[1] == -e[6])
        assertTrue(e[7] * e[2] == e[5])
        assertTrue(e[7] * e[3] == e[4])
        assertTrue(e[7] * e[4] == -e[3])
        assertTrue(e[7] * e[5] == -e[2])
        assertTrue(e[7] * e[6] == e[1])
        assertTrue(e[7] * e[7] == -e[0])
        assertTrue(e[7] * e[8] == e[15])
        assertTrue(e[7] * e[9] == e[14])
        assertTrue(e[7] * e[10] == -e[13])
        assertTrue(e[7] * e[11] == -e[12])
        assertTrue(e[7] * e[12] == e[11])
        assertTrue(e[7] * e[13] == e[10])
        assertTrue(e[7] * e[14] == -e[9])
        assertTrue(e[7] * e[15] == -e[8])
        assertTrue(e[8] * e[0] == e[8])
        assertTrue(e[8] * e[1] == -e[9])
        assertTrue(e[8] * e[2] == -e[10])
        assertTrue(e[8] * e[3] == -e[11])
        assertTrue(e[8] * e[4] == -e[12])
        assertTrue(e[8] * e[5] == -e[13])
        assertTrue(e[8] * e[6] == -e[14])
        assertTrue(e[8] * e[7] == -e[15])
        assertTrue(e[8] * e[8] == -e[0])
        assertTrue(e[8] * e[9] == e[1])
        assertTrue(e[8] * e[10] == e[2])
        assertTrue(e[8] * e[11] == e[3])
        assertTrue(e[8] * e[12] == e[4])
        assertTrue(e[8] * e[13] == e[5])
        assertTrue(e[8] * e[14] == e[6])
        assertTrue(e[8] * e[15] == e[7])
        assertTrue(e[9] * e[0] == e[9])
        assertTrue(e[9] * e[1] == e[8])
        assertTrue(e[9] * e[2] == -e[11])
        assertTrue(e[9] * e[3] == e[10])
        assertTrue(e[9] * e[4] == -e[13])
        assertTrue(e[9] * e[5] == e[12])
        assertTrue(e[9] * e[6] == e[15])
        assertTrue(e[9] * e[7] == -e[14])
        assertTrue(e[9] * e[8] == -e[1])
        assertTrue(e[9] * e[9] == -e[0])
        assertTrue(e[9] * e[10] == -e[3])
        assertTrue(e[9] * e[11] == e[2])
        assertTrue(e[9] * e[12] == -e[5])
        assertTrue(e[9] * e[13] == e[4])
        assertTrue(e[9] * e[14] == e[7])
        assertTrue(e[9] * e[15] == -e[6])
        assertTrue(e[10] * e[0] == e[10])
        assertTrue(e[10] * e[1] == e[11])
        assertTrue(e[10] * e[2] == e[8])
        assertTrue(e[10] * e[3] == -e[9])
        assertTrue(e[10] * e[4] == -e[14])
        assertTrue(e[10] * e[5] == -e[15])
        assertTrue(e[10] * e[6] == e[12])
        assertTrue(e[10] * e[7] == e[13])
        assertTrue(e[10] * e[8] == -e[2])
        assertTrue(e[10] * e[9] == e[3])
        assertTrue(e[10] * e[10] == -e[0])
        assertTrue(e[10] * e[11] == -e[1])
        assertTrue(e[10] * e[12] == -e[6])
        assertTrue(e[10] * e[13] == -e[7])
        assertTrue(e[10] * e[14] == e[4])
        assertTrue(e[10] * e[15] == e[5])
        assertTrue(e[11] * e[0] == e[11])
        assertTrue(e[11] * e[1] == -e[10])
        assertTrue(e[11] * e[2] == e[9])
        assertTrue(e[11] * e[3] == e[8])
        assertTrue(e[11] * e[4] == -e[15])
        assertTrue(e[11] * e[5] == e[14])
        assertTrue(e[11] * e[6] == -e[13])
        assertTrue(e[11] * e[7] == e[12])
        assertTrue(e[11] * e[8] == -e[3])
        assertTrue(e[11] * e[9] == -e[2])
        assertTrue(e[11] * e[10] == e[1])
        assertTrue(e[11] * e[11] == -e[0])
        assertTrue(e[11] * e[12] == -e[7])
        assertTrue(e[11] * e[13] == e[6])
        assertTrue(e[11] * e[14] == -e[5])
        assertTrue(e[11] * e[15] == e[4])
        assertTrue(e[12] * e[0] == e[12])
        assertTrue(e[12] * e[1] == e[13])
        assertTrue(e[12] * e[2] == e[14])
        assertTrue(e[12] * e[3] == e[15])
        assertTrue(e[12] * e[4] == e[8])
        assertTrue(e[12] * e[5] == -e[9])
        assertTrue(e[12] * e[6] == -e[10])
        assertTrue(e[12] * e[7] == -e[11])
        assertTrue(e[12] * e[8] == -e[4])
        assertTrue(e[12] * e[9] == e[5])
        assertTrue(e[12] * e[10] == e[6])
        assertTrue(e[12] * e[11] == e[7])
        assertTrue(e[12] * e[12] == -e[0])
        assertTrue(e[12] * e[13] == -e[1])
        assertTrue(e[12] * e[14] == -e[2])
        assertTrue(e[12] * e[15] == -e[3])
        assertTrue(e[13] * e[0] == e[13])
        assertTrue(e[13] * e[1] == -e[12])
        assertTrue(e[13] * e[2] == e[15])
        assertTrue(e[13] * e[3] == -e[14])
        assertTrue(e[13] * e[4] == e[9])
        assertTrue(e[13] * e[5] == e[8])
        assertTrue(e[13] * e[6] == e[11])
        assertTrue(e[13] * e[7] == -e[10])
        assertTrue(e[13] * e[8] == -e[5])
        assertTrue(e[13] * e[9] == -e[4])
        assertTrue(e[13] * e[10] == e[7])
        assertTrue(e[13] * e[11] == -e[6])
        assertTrue(e[13] * e[12] == e[1])
        assertTrue(e[13] * e[13] == -e[0])
        assertTrue(e[13] * e[14] == e[3])
        assertTrue(e[13] * e[15] == -e[2])
        assertTrue(e[14] * e[0] == e[14])
        assertTrue(e[14] * e[1] == -e[15])
        assertTrue(e[14] * e[2] == -e[12])
        assertTrue(e[14] * e[3] == e[13])
        assertTrue(e[14] * e[4] == e[10])
        assertTrue(e[14] * e[5] == -e[11])
        assertTrue(e[14] * e[6] == e[8])
        assertTrue(e[14] * e[7] == e[9])
        assertTrue(e[14] * e[8] == -e[6])
        assertTrue(e[14] * e[9] == -e[7])
        assertTrue(e[14] * e[10] == -e[4])
        assertTrue(e[14] * e[11] == e[5])
        assertTrue(e[14] * e[12] == e[2])
        assertTrue(e[14] * e[13] == -e[3])
        assertTrue(e[14] * e[14] == -e[0])
        assertTrue(e[14] * e[15] == e[1])
        assertTrue(e[15] * e[0] == e[15])
        assertTrue(e[15] * e[1] == e[14])
        assertTrue(e[15] * e[2] == -e[13])
        assertTrue(e[15] * e[3] == -e[12])
        assertTrue(e[15] * e[4] == e[11])
        assertTrue(e[15] * e[5] == e[10])
        assertTrue(e[15] * e[6] == -e[9])
        assertTrue(e[15] * e[7] == e[8])
        assertTrue(e[15] * e[8] == -e[7])
        assertTrue(e[15] * e[9] == e[6])
        assertTrue(e[15] * e[10] == -e[5])
        assertTrue(e[15] * e[11] == -e[4])
        assertTrue(e[15] * e[12] == e[3])
        assertTrue(e[15] * e[13] == e[2])
        assertTrue(e[15] * e[14] == -e[1])
        assertTrue(e[15] * e[15] == -e[0])
    }

    @Test
    fun `product of basis equals negative one`() {
        var p = 1.toSedenion()
        e.forEach { p *= it }
        assertEquals(p, (-1).toSedenion())
    }

    @Test
    fun `multiplying zero divisor pairs equal zero`() {
        fun pairProduct(pair: Pair<Sedenion, Sedenion>) = pair.first * pair.second

        val zero = 0.toSedenion()
        val zeroDivisorPairs = listOf(
            Pair(Sedenion(s1 = 1, sA = 1), Sedenion(s5 = 1, sE = 1)),
            Pair(Sedenion(s1 = 1, sB = 1), Sedenion(s4 = 1, sE = 1)),
            Pair(Sedenion(s1 = 1, sC = 1), Sedenion(s2 = 1, sF = 1))
        )
        assertEquals(zero, pairProduct(zeroDivisorPairs[0]))
        assertEquals(zero, pairProduct(zeroDivisorPairs[1]))
        assertEquals(zero, pairProduct(zeroDivisorPairs[2]))
    }

    @Test
    fun `zero divisors`() {
        val s1 = Sedenion(s3 = 1, sA = 1)
        val s2 = Sedenion(s6 = 1, sF = -1)
        println(s1 * s2)
        println(s2 * s1)
    }
}